#!/usr/bin/env python3

import sys
import subprocess


def main():
    should_run = (
        '--force' in sys.argv
        or any(line.split()[2].endswith('/master') for line in sys.stdin)
    )
    if should_run:
        subprocess.run('ci/test.sh', check=True)
        subprocess.run('ci/lint.sh', check=True)
        subprocess.run('ci/docstyle.sh', check=True)
        subprocess.run(['coverage', 'html'], check=True)
        subprocess.run(['coverage', 'report'], check=True)


if __name__ == '__main__':
    main()
